project:
  type: website

website:
  title: "Eleanor"
  navbar:
    search: true
    left:
      - href: about.qmd
        text: Getting Started
      - href: docs.qmd
        text: Docs
      - href: examples.qmd
        text: Examples

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
